### ISSUE TITLE
Does not support older PHP versions

### ISSUE THREAD

**Issue by cnizzardini** [maratbn/LoginRequirePress#4]
The plugin uses short hand array syntax [] instead of array(). I updated the plugin locally to work on an older install. Might you consider doing this yourself as some people just might not use this since it errors out on activation.

Thanks for making this plugin public!

**Comment by maratbn** [comment]
Appreciate the feedback, but I'm surprised that even with that change you were still able to run it on PHP <= 5.4, as the plugin also uses short echo tags, which to my knowledge are disabled on < 5.4 by default.

Plugin requires PHP >= 5.4  I know the REQUIREMENTS erroneously say 5.3 but I'm planning to fix that in the next release.

5.4 was released in 2012.  The way I see it supporting anything older for a tiny minority is just not worth it..  There's an expectation that people should keep their systems upgraded, and supporting software that's 3+ years old is very reasonable.  On the other hand, in my opinion, asking that software that's 4+ years old still be supported is not reasonable.  And in general it's not a good practice to run very old software as it may have known exploits.

Once in a while I do get reports from people running very old PHP, so that makes me curious.
Why are you still running 5.3 (my guess b/c /w < 5.3 you'd have even more problems), and what is preventing you from upgrading?

-- Marat

**Comment by maratbn** [comment]
Duplicate of #1

**Comment by maratbn** [comment]
But if you'd like to send a pull request with your work, I'll put it in a special branch for whoever really needs to run PHP 5.3.

**Comment by cnizzardini** [comment]
Because I wear many hats at my job and haven't gotten around to upgrading
our servers :-( It's easy to enable/disable shorttags as well.
